### ISSUE TITLE
Titles track and/or artwork

### ISSUE THREAD

**Issue by fmarzocca** [forscher21/mopidy-cd#13]
Hi,

I am using this plugin on my Raspberry/mopidy station with IRIS webclient.

I am noticing that very often the title tracks are not listed (only Track #) and/or the album artwork is not grabbed, with no relevant messages in the log.

Is there a way I can improve this?

**Comment by vonZeppelin** [comment]
Hi @fmarzocca,

This extension uses [MusicBrainz](https://musicbrainz.org/) DB to identify discs and retrieve cover arts. Can you check that MusicBrainz knows about your CDs first? Can you post DiscIDs of your CDs?

**Comment by fmarzocca** [comment]
Yes, I have verified. It is a MusicBrainz issue. Not all CDs are there and some album is not exactly identical to mine. Thanks.
